// Level: Chase.
// Map data automatically generated by Processing.
// Each pair of floats in an array is a coordinate for a tile, in tilemap space.

float staticSpikes[78] = {
	1.0f, 6.0f, 2.0f, 6.0f, 3.0f, 6.0f, 1.0f, 7.0f, 2.0f, 7.0f, 1.0f, 8.0f, 0.0f, 15.0f, 1.0f, 15.0f, 2.0f, 15.0f, 3.0f, 15.0f, 0.0f, 16.0f, 1.0f, 16.0f, 2.0f, 16.0f, 14.0f, 16.0f, 15.0f, 16.0f, 16.0f, 16.0f, 
	17.0f, 16.0f, 18.0f, 16.0f, 19.0f, 16.0f, 0.0f, 17.0f, 1.0f, 17.0f, 15.0f, 20.0f, 1.0f, 29.0f, 2.0f, 29.0f, 3.0f, 29.0f, 4.0f, 29.0f, 6.0f, 31.0f, 7.0f, 31.0f, 0.0f, 36.0f, 0.0f, 37.0f, 0.0f, 38.0f, 0.0f, 39.0f, 
	0.0f, 40.0f, 12.0f, 42.0f, 0.0f, 43.0f, 13.0f, 43.0f, 0.0f, 44.0f, 0.0f, 45.0f, 0.0f, 46.0f
};
float redSpikes[22] = {
	19.0f, 2.0f, 20.0f, 3.0f, 13.0f, 10.0f, 14.0f, 11.0f, 6.0f, 21.0f, 7.0f, 21.0f, 8.0f, 21.0f, 18.0f, 38.0f, 19.0f, 38.0f, 20.0f, 38.0f, 21.0f, 38.0f
};
float blueSpikes[20] = {
	4.0f, 6.0f, 5.0f, 6.0f, 6.0f, 6.0f, 7.0f, 6.0f, 20.0f, 10.0f, 19.0f, 11.0f, 12.0f, 27.0f, 13.0f, 27.0f, 14.0f, 27.0f, 15.0f, 27.0f
};
float abilities[10] = {
	2.0f, 12.0f, 11.0f, 21.0f, 3.0f, 27.0f, 13.0f, 35.0f, 7.0f, 38.0f
};

AddStaticSpikes(staticSpikes, 39);
AddRedSpikes(redSpikes, 11, redDimension);
AddBlueSpikes(blueSpikes, 10, blueDimension);
AddAbilities(abilities, 5);
